# Generated by Django 2.2.4 on 2019-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190325_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('', 'Unspecified')], default='', help_text='Birth Sex Gender', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender_identity',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TMF', 'Transgender Male to Female'), ('TFM', 'Transgender Female to Male'), ('', 'Unspecified')], default='', help_text='Gender Identity', max_length=3),
        ),
    ]
