# Generated by Django 2.2.4 on 2019-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhirproxy', '0003_auto_20190222_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='use_client_credentials',
            field=models.BooleanField(blank=True, default=False, help_text='When checked, OAuth2 client credentials to access the FHIR source using values in settings.py'),
        ),
    ]
