# Generated by Django 2.2.4 on 2019-09-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fhirproxy', '0004_crosswalk_use_client_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_patient_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='fhir_source',
            field=models.CharField(blank=True, default='https://nwt-staging.azurehealthcareapis.com/', max_length=512, verbose_name='The backend FHIR server to proxy'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='use_client_credentials',
            field=models.BooleanField(blank=True, default=False, help_text='When checked, OAuth2 client credentials to\n                                             access the FHIR source using values in settings.py'),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crosswalk',
            name='user_id_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
