# Generated by Django 2.1.2 on 2019-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0007_auto_20190408_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='fhir_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hixnyprofile',
            name='fhir_content_embellish',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hixnyprofile',
            name='terms_of_service',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='hixnyprofile',
            name='mrn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='hixnyprofile',
            name='user_accept',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
