# Generated by Django 2.1.2 on 2019-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hixny', '0008_auto_20190515_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='hixnyprofile',
            name='cda_content_md5hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='hixnyprofile',
            name='fhir_content_embellish',
            field=models.TextField(blank=True, default='', help_text='The raw CDA2FHIR translation with enhanced data.'),
        ),
    ]
