# Generated by Django 2.2.4 on 2019-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hieprofile',
            name='organization_name',
            field=models.CharField(blank=True, default='HIXNY API', max_length=64),
        ),
    ]
